version: "3"

services:
  logs_flask:
    container_name: logs_flask
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: /app/entrypoint.sh
    volumes:
      - ./backend:/app
    env_file:
      - .env
    ports:
      - "${FLASK_PORT}:5000"
    networks:
      - logs_network
    depends_on:
      - logs_postgres

  logs_nginx:
    image: nginx:1.25.2-alpine
    container_name: logs_nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./certs:/etc/ssl/certs:ro
      - ./nginx/prod.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - logs_flask
    networks:
      - logs_network
  
  logs_postgres:
    image: postgres:14.4-bullseye
    container_name: logs_postgres
    networks:
      - logs_network
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  logs_network:
    driver: bridge

volumes:
  postgres_data:
